# Generated by Django 3.1.11 on 2021-05-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studypage',
            options={'verbose_name': 'Study page'},
        ),
    ]
