# Generated by Django 3.1.8 on 2021-05-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiepage',
            name='very_cool_test_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
