# Generated by Django 3.1.8 on 2021-04-27 22:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_auto_20201027_2246"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="articles_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="articles_linktext",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="articles_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="featured_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="featured_pages_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_button_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_button_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_introduction",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_linktext",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="pages_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="pages_linktext",
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.core.blocks.CharBlock(form_classname="full title"),
                    ),
                    ("subheading", wagtail.core.blocks.RichTextBlock()),
                ]
            ),
        ),
    ]
