# Generated by Django 3.1.11 on 2021-05-18 23:05

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matrikelnummer",
                    models.CharField(
                        blank=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters and digits only.",
                        max_length=36,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator
                        ],
                        verbose_name="matrikelnummer",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters and digits only.",
                        max_length=36,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator
                        ],
                        verbose_name="telegram username",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.IntegerField(
                        error_messages={
                            "unique": "A user with that user_id already exists."
                        },
                        help_text="Required. 64 Bit Integer. Digits only.",
                        verbose_name="user id",
                    ),
                ),
                (
                    "registration_token",
                    models.CharField(
                        blank=True,
                        error_messages={
                            "unique": "A user with that matrikelnummer already exists."
                        },
                        help_text="Required. 36 digits long. Digits only.",
                        max_length=36,
                        null=True,
                        verbose_name="registration token",
                    ),
                ),
                (
                    "is_member",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this member should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="is member",
                    ),
                ),
                (
                    "user",
                    modelcluster.fields.ParentalKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
