# Generated by Django 2.2 on 2020-10-27 21:46

import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("wagtailcore", "0052_pagelogentry")]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                ("social_text", models.CharField(blank=True, max_length=255)),
                (
                    "listing_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the page title used when this page appears in listings",
                        max_length=255,
                    ),
                ),
                (
                    "listing_summary",
                    models.CharField(
                        blank=True,
                        help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.",
                        max_length=255,
                    ),
                ),
                ("city", models.CharField(max_length=255, null=True)),
                ("zip_code", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("telephone", models.CharField(max_length=255, null=True)),
                ("telefax", models.CharField(max_length=255, null=True)),
                ("vat_number", models.CharField(max_length=255, null=True)),
                (
                    "whatsapp_telephone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "whatsapp_contactline",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tax_id", models.CharField(max_length=255, null=True)),
                ("court_of_registry", models.CharField(max_length=255, null=True)),
                ("place_of_registry", models.CharField(max_length=255, null=True)),
                ("trade_register_number", models.CharField(max_length=255, null=True)),
                ("ownership", models.CharField(max_length=255, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("copyrightholder", models.CharField(max_length=255, null=True)),
                ("about", wagtail.core.fields.RichTextField(null=True)),
                ("privacy", wagtail.core.fields.RichTextField(null=True)),
                (
                    "sociallinks",
                    wagtail.core.fields.StreamField(
                        [
                            (
                                "link",
                                wagtail.core.blocks.URLBlock(
                                    help_text="Important! Format https://www.domain.tld/xyz"
                                ),
                            )
                        ]
                    ),
                ),
                ("hero_title", models.CharField(max_length=80, null=True)),
                ("hero_introduction", models.CharField(max_length=255, null=True)),
                (
                    "hero_button_text",
                    models.CharField(blank=True, max_length=55, null=True),
                ),
                (
                    "articles_title",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "articles_linktext",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "featured_pages_title",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "pages_linktext",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("news_title", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "news_linktext",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "articles_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.Page",
                    ),
                ),
            ],
            options={"verbose_name": "Home Page"},
            bases=("wagtailcore.page", models.Model),
        )
    ]
